# Generated by Django 4.2.7 on 2026-05-29 09:26

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=settings.models.profile_avatar_upload_to),
        ),
    ]
